DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Userdata;

CREATE TABLE Users (
	ID INTEGER PRIMARY KEY,
	Username TEXT
);

CREATE TABLE Userdata (
	UserID INTEGER PRIMARY KEY,
	Name TEXT,
	Surname TEXT,
	Description TEXT
);
